<footer>
    <?php
        $footerData =  $this->footer()->footerItens();
        
        
       // print_r($footerData['links']);
        
        $setcolumn = 0;
        $setSessionItems = count($footerData['links']);
        
        
        echo '<div class="info first"><ul><li class="title">Info</li>';
        
        
        foreach ($footerData['links'] as $links) {
            
            
            if($setcolumn <= 10){
                
                echo '<li>'.$links['nome'].'</li>';
                $setcolumn++;
                
            } else{
                
                 echo '</ul><div class="info"><ul>';
                  $setcolumn = 0;
            }
            
            if($setcolumn == 22){
                
                echo '</ul></div>';
            }
            
        }
        
        echo '</ul></div>';
        
        
    ?>
    
    <div class="info-container">
<!--        <div class="info first">
             List group 
            <ul>
                <li class="title">Info</li>
                <li>Cras justo odio</li>
                <li>Entrega</li>
                <li>Garantia estendida</li>
                <li>Assessoria de imprensa</li>
                <li>Investidores</li>
                <li>Companhia verde</li>

            </ul>
        </div>

        <div class="info">

         List group 
        <ul>
            <li class="title">FAQ</li>
            <li>Cras justo odio</li>
            <li>Entrega</li>
            <li>Garantia estendida</li>
            <li>Assessoria de imprensa</li>
            <li>Investidores</li>
            <li>Companhia verde</li>

        </ul>
        </div>

        <div class="info">

         List group 
        <ul>
            <li class="title">Loja</li>
            <li>Cras justo odio</li>
            <li>Entrega</li>
            <li>Garantia estendida</li>
            <li>Assessoria de imprensa</li>
            <li>Investidores</li>
            <li>Companhia verde</li>

        </ul>
        </div>-->
        <div class="clear"></div>

        <div class="credit-cards-container"></div>

        <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
    </div>
</footer>