<span ng-controller="modalUsersAssistente">
    <script>
        $(document).ready(function () {

            $('button.close').click(function () {
                $('form').trigger("reset");
                document.getElementById("messageLogin").textContent = "";
            });

            $('input#loginInput').focus(function () {
                document.getElementById("messageLogin").textContent = "";
            });
        });

        function resetMsg() {
           // document.getElementById("messageLogin").textContent = "";
        }

        function resetMsgCadastro() {
            //document.getElementById("messageCadastro").textContent = "";
            //  document.getElementById("messageCadastrar1").textContent = "";
        }
    </script>
    <!--angular -->

        <div class="topbar-container">
            <header id="site-topbar" class="site-topbar fixed clearfix" itemscope itemtype="http://schema.org/WebSite">
                <div class="logo">
                    <div style=" overflow-y: hidden; height: 60px;">
                        <a href="/"><?php //echo '<img src="/images/' . $logo_shop . '" width="132">'; ?></a>
                    </div>
                </div>
                <div class="wraper-right-icons">

            <div ng-controller="initDropDown" class="session-buttom" ng-mouseover="showSession()" ng-click="goCart()" ng-mouseleave="hideSession()" id="showCart" >
                <span class="glyphicon glyphicon-shopping-cart"></span>
                <div ng-cloak ng-show="sessionIsVisible" class="dropdown-default cart-info">
                    Seu carrinho esta vazio!
                </div>
            </div>
                    <div class="cart">
                        <!--#############################################################-->
                        <span id="cartInfo">


                            <script>
                                angular.module('ui.bootstrap.app').controller('initDropDown', function ($scope, $interval) {
                                    var c = 0;
                                    $scope.showSession = function () {
                                        $scope.sessionIsVisible = true;
                                    };

                                    $scope.hideSession = function () {
                                        //alert(1);
                                        $scope.sessionIsVisible = false;
                                    };

                                    $scope.goCart = function () {
                                        //alert(1);
                                        window.location.href = '/checkout';
                                    };

                                    $scope.showCartBtn = function () {
                                        $scope.cartIsVisible = true;
                                        $("div#cart").load("/cart/queryCart");
                                        var timer = $interval(function () {
                                            $scope.counter = "exec " + c + ".";
                                            if (c == 50) {
                                                $scope.cartIsVisible = false;
                                                $interval.cancel(timer);
                                                c = 0;
                                            }
                                            c++;
                                        }, 100);
                                    };
                                });
                            </script>
                        </span>
                    </div>

                    <?php
                    $menuData =  $this->sessions()->checkSession();

                    if (!$menuData) {
                        echo '<div class="login">
                                    <div class="wrapper">
                                    <a href="" ng-click="open(\'sm\', \'1\')" id="loginOpen"><div style="position:relative; float:left;"><span class="glyphicon glyphicon-log-in"></span>&nbsp; Entre</div></a>&nbsp;
                                    <span class="color">ou</span>&nbsp;
                                    <a href="" ng-click="open(\'sm\', \'0\')">Cadastre-se</a>
                              </div>
                            </div>';
                    }
                    ?>

                    <?php
                    if ($menuData) {

                        $session = new \Zend\Session\Container('sessionUser');

                        echo '
                            <div ng-controller="initDropDown" class="session-buttom" ng-mouseover="showSession()" ng-mouseleave="hideSession()" id="showCart" >
                                <span class="glyphicon glyphicon-user"></span>
                                
                                <div ng-cloak ng-show="sessionIsVisible" class="dropdown-default user-actions">
                                    <div class="header-dropdown">'.$session->nomeUser .'</div>
                                    <div class="content">
                                        <div class=""><a href="#"><span class="glyphicon glyphicon-user"></span> Minha conta</a> </div>
                                        <div class=""><a href="#"><span class="glyphicon glyphicon-th-large"></span> Pedidos</a></div>
                                        <div class=""><a href="/logout?hash='.$session->keyUser.'"><span class="glyphicon glyphicon-off"></span> Sair</a></div>
                                    </div>

                                </div>                                
                            </div>                        
                        ';
                    }
                    ?>
</span>
</div>
</header><!--FEcha #site-topbar################-->
</div><!--fecha div.page###############-->


<!-- === Modal register ==== -->
<script type="text/ng-template" id="modalCadastro.html">

    <div>
        <div class="wm-sign-in">
            <a title="Fechar" type="button" class="close" ng-click="cancel()" style="display:block; text-decoration:none; cursor:pointer; font-size:30px; position:relative;top:-8px; float:right; height:20px;">×</a>
            <div class="sign-in-wrapper">
                <form class="client-sign-in" id="client-sign-up cadastrarCtrl" autocomplete="off" novalidate="novalidate" >

                    <fieldset ng-controller="cadastrarCtrl">
                        <div class="title">Preencha os campos</div>

                        <div class="client-name">
                            <span class="icon"></span>
                            <input id="cadNome" ng-blur="validate('cadNome')" type="text" class="input-box product-ipt-notifyme-client-name" ng-model="nome" placeholder="Nome completo" onfocus="resetMsgCadastro();" />

                            <span class="icon-login-check checkmark" id="cadNome" ng-show="cadNomeOk" style="display: block"></span>
                            <span class="icon-field-error checkmark" id="cadNomeErr" ng-show="cadNomeErr" style="display: block"></span>
                            <span class="wm-tooltip wm-notify-error bottom" id="cadNomeMsg"><span class="wm-tooltip-arrow"></span><span class="wm-tooltip-arrow-shadow"></span><span class="wm-tooltip-content" id="cadNomeMsgSlot"></span></span>
                        </div>

                        <div class="client-user-name">
                            <span class="icon"></span>

                            <input type="text" id="cadEmail" ng-blur="validate('cadEmail')" class="input-box" ng-model="email" placeholder="E-mail" onfocus="resetMsgCadastro();" />
                            <span class="icon-login-check checkmark" id="cadEmail" ng-model="cadEmailOk" ng-show="cadEmailOk" style="display: block"></span>
                            <span class="icon-field-error checkmark" id="cadEmailErr" ng-show="cadEmailErr" style="display: block"></span>
                            <span class="wm-tooltip wm-notify-error bottom" id="cadEmailMsg"><span class="wm-tooltip-arrow"></span><span class="wm-tooltip-arrow-shadow"></span><span class="wm-tooltip-content" id="cadEmailMsgSlot"></span></span>

                        </div>

                        <div class="client-cpfcnpj">
                            <span class="icon"></span>

                            <input type="text" id="cadCpfCnpj" ng-blur="validate('cadCpfCnpj')" class="input-box" ng-model="cpf_cnpj" placeholder="CPF ou CNPJ" onfocus="resetMsgCadastro();" />

                            <span class="icon-login-check checkmark" id="cadCpfCnpj" ng-show="cadCpfCnpjOk" style="display: block"></span>
                            <span class="icon-field-error checkmark" id="cadCpfCnpjErr" ng-show="cadCpfCnpjErr" style="display: block"></span>
                            <span class="wm-tooltip wm-notify-error bottom" id="cadCpfCnpjMsg"><span class="wm-tooltip-arrow"></span><span class="wm-tooltip-arrow-shadow"></span><span class="wm-tooltip-content" id="cadCpfCnpjMsgSlot"></span></span>

                        </div>

                        <div class="client-phone">
                            <span class="icon"></span>

                            <input type="text" id="cadPhone" ng-blur="validate('cadPhone')" class="input-box" ng-model="telefone" placeholder="(DDD) xxxx-xxxx" onfocus="resetMsgCadastro();" />

                            <span class="icon-login-check checkmark" id="cadPhone" ng-show="cadPhoneOk" style="display: block"></span>
                            <span class="icon-field-error checkmark" id="cadPhoneErr" ng-show="cadPhoneErr" style="display: block"></span>
                            <span class="wm-tooltip wm-notify-error bottom" id="cadPhoneMsg"><span class="wm-tooltip-arrow"></span><span class="wm-tooltip-arrow-shadow"></span><span class="wm-tooltip-content" id="cadPhoneMsgSlot"></span></span>
                        </div>

                        <div class="new-client-pwd">
                            <span class="icon"></span>

                            <input type="password" id="cadPass" ng-blur="validate('cadPass')" class="input-box" ng-model="senha_1" placeholder="Senha" onfocus="resetMsgCadastro();" />

                            <span class="icon-login-check checkmark" id="cadPass" ng-show="cadPassOk" style="display: block"></span>
                            <span class="icon-field-error checkmark" id="cadPassErr" ng-show="cadPassErr" style="display: block"></span>
                            <span class="wm-tooltip wm-notify-error bottom" id="cadPassMsg"><span class="wm-tooltip-arrow"></span><span class="wm-tooltip-arrow-shadow"></span><span class="wm-tooltip-content" id="cadPassMsgSlot"></span></span>

                        </div>

                        <div class="new-client-pwd">
                            <span class="icon"></span>

                            <input type="password" id="cadPassC" ng-blur="validate('cadPassC')" class="input-box" ng-model="senha_c" placeholder="Confirmar Senha" onfocus="resetMsgCadastro();" />

                            <span class="icon-login-check checkmark" id="cadPassC" ng-show="cadPassC_Ok" style="display: block"></span>
                            <span class="icon-field-error checkmark" id="cadPassCErr" ng-show="cadPassCErr" style="display: block"></span>
                            <span class="wm-tooltip wm-notify-error bottom" id="cadPassCMsg"><span class="wm-tooltip-arrow"></span><span class="wm-tooltip-arrow-shadow"></span><span class="wm-tooltip-content" id="cadPassCMsgSlot"></span></span>

                        </div>

                        <div style="clear:both;"></div>

                        <div style="margin-top: 10px;">
                            <div style=" font-size: 11px; text-align: center; font-weight: bold; margin-top: 8px; color: #f00; height: 10px; margin-bottom: 8px;">
                                <span id="messageCadastro" ng-model="messageCadastro">{{messageCadastro}}</span>
                                <div class="loading" ng-show="loading" ng-model="loader" style="margin: 0 auto;"></div>
                            </div>

                            <div align="center" style="margin-bottom: 10px; position: relative;">
                                <button ng-click="cadastrar()" ng-disabled="registerBtnDisabled" class="btn btn-primary" style="font-weight: bold; width: 99%;">Cadastrar</button><br>
                            </div>
                        </div>

                        <div style="font-size: 12px; color: #888" >
                            <span style="position: relative;" >
                                <input type="checkbox" ng-model="newsletter" ng-checked="true" />
                            </span>
                            <span>  Desejo receber ofertas por e-mail.</span>
                        </div>

                        <div style=" font-size: 12px; color: #888;">

                            <hr size="1" style="color: #888;">
                            Ao criar uma conta, você concorda com nossos termos de uso, condições, política de privacidade e que tem pelo menos 16 anos de idade.

                        </div>

                    </fieldset>
                </form></div>
        </div>
    </div>


</script>

<div>

<script type="text/ng-template" id="modalLogin.html">

    <div class="wm-sign-in clearfix">
        <a title="Fechar" type="button" class="close" ng-click="cancel()"
           style="display:block; text-decoration:none; cursor:pointer; font-size:30px; position:relative; float:right;top:-8px; height:20px;">×</a>
        <div class="title">Entrar</div>
        <div id="alert-signin-error" class="alert alert-danger alert-dismissable hide"><span
                    class="icon-wm-warning" ></span><span id="message">Usuário ou senha inválidos.</span></div>
        <div class="sign-in-wrapper">

            <form id="loginForm client-sign-in" name="login" class="client-sign-in" novalidate="novalidate">
                <fieldset ng-controller="loginFormModal" >
                    <div class="client-user-name">
                        <span class="icon"></span>
                        <input type="text" class="input-box" name="email" ng-model="email" id="loginInput"
                               onfocus="resetMsg();" placeholder="E-mail, CPF ou CNPJ"/>

                    </div>

                    <div class="new-client-pwd">
                        <span class="icon"></span>

                        <input type="password" class="input-box" ng-model="senha" id="pass" placeholder="Senha"
                               onfocus="resetMsg();"/>
                    </div>

                    <div style="clear:both;"></div>

                    <div style="">
                        <div style="font-size: 11px; text-align: center; font-weight: bold; margin-top: 8px; color: #f00; height: 10px; margin-bottom: 8px;">

                            <span id="messageLogin" ng-model="messageLogin">{{messageLogin}}</span>
                            <div class="loading" ng-show="loading" ng-model="loader"
                                 style="padding: 1px; height: 16px; width: 16px;"></div>
                        </div>

                        <div align="center" style="margin-bottom: 10px;">
                            <button ng-click="entrar()" class="btn btn-primary" style="font-weight: bold; width: 99%;">
                                Entrar
                            </button>
                            <br>
                        </div>
                    </div>

                    <div class="form-group" style="font-size: 12px; color: #888">
                        <span style="position: relative; top: 2px;"><input type="checkbox" id="logged" value="1" ng-model="conectado"/></span>
                        <span>  Continuar conectado</span>
                    </div>
                    <div style="font-size: 12px; color: #888">
                        <a href="" ng-click="switchLoginRecover()">Esqueci minha senha</a>
                    </div>

                </fieldset>
            </form>

        </div>
        <div class="sign-in-footer">
            Não tem conta em nossa Loja?
            <div class="form-group links" style="font-size: 12px; color: #888; text-align: center; padding-top:4px;">
                <a class="links" href="" ng-click="switchCadastroModal()" style="font-size: 20px;"><span> Cadastre-se aqui</span>
                </a>
            </div>

        </div>
    </div>
</script>


<script type="text/ng-template" id="modalRecover.html">
    <div class="wm-sign-in clearfix">
        <a title="Fechar" type="button" class="close" ng-click="cancel()"
           style="display:block; text-decoration:none; cursor:pointer; font-size:30px; position:relative; float:right; top:-8px; height:20px;">×</a>
        <div class="title">Esqueci minha senha</div>
        <div id="alert-signin-error" class="alert alert-danger alert-dismissable hide signup-error"><span
                    class="icon-wm-warning"></span>&nbsp;<span id="message">Ops! Tente Novamente.</span></div>
        <div class="sign-in-wrapper">

            <form id="noticeRecoverCtrl">
                <fieldset ng-controller="recoverCtrl">

                    <div class="label">Digite seu E-mail, CPF ou CNPJ para receber as instruções e criar uma nova
                        senha
                    </div>
                    <div class="client-user-name">
                        <span class="icon"></span>
                        <input id="signinClientName" ng-model="email" onfocus="resetMsgCadastro();"
                               class="input-box email-fp" type="text" maxlength="100" name="signinClientName"
                               placeholder="E-mail, CPF ou CNPJ" style="width:430px"><span id="checkmark"
                                                                                           class="icon-login-check checkmark validate"></span><span
                                id="toolTip" class="wm-tooltip wm-notify-error left forgot" style="display: none;"><span
                                    class="wm-tooltip-arrow"></span><span class="wm-tooltip-arrow-shadow"></span><span
                                    class="wm-tooltip-content">&nbsp;</span></span></div>
                    <div style="">
                        <div style=" font-size: 11px; text-align: center; font-weight: bold; margin-top: 8px; color: #f00; height: 10px; margin-bottom: 8px;">
                            <span id="messageCadastrar1"></span>
                            <div class="loading" id="loading" ng-show="loading" ng-model="loader"
                                 style="padding: 1px; height: 16px; width: 16px;"></div>
                        </div>

                        <div class="forgot-password-actions">
                            <input id="signinButtonSend" ng-click="recover()" class="btn btn-primary" value="Enviar"
                                   type="submit" name="signinButtonSend"> ou <a class="closeable" ng-click="cancel()"
                                                                                href="#">Cancelar</a></div>
                    </div>

                </fieldset>
            </form>
        </div>


    </div>
</script>


<script>
    //angular.module('ui.bootstrap.app', ['ngAnimate', 'ui.bootstrap']);
    angular.module('ui.bootstrap.app').controller('modalUsersAssistente', function ($scope, $uibModal, $log, $rootScope) {

        //############open modal recover senha#############
        $scope.$on('modalRecover', function (event, data) {
            $scope.open('lg', '2');
        });

        $scope.$on('modalCadastro', function (event, data) {
            $scope.open('sm', '0');
        });

        $scope.items = ['item1', 'item2', 'item3'];

        $scope.animationsEnabled = true;

        $scope.open = function (size, type) {
            var tipoModal = type;

            if (tipoModal == 0) {
                var setTemplate = 'modalCadastro.html';
            } else if (tipoModal == 1) {
                var setTemplate = 'modalLogin.html';
            } else if (tipoModal == 2) {
                var setTemplate = 'modalRecover.html';
            } else if (tipoModal == 3) {
                var setTemplate = 'modalNewsletter.html';
            } else if (tipoModal == 4) {
                var setTemplate = 'modalAtendimento.html';
            } else if (tipoModal >= 50) {
                var setTemplate = 'modalInfo' + tipoModal + '.html';
            }

            var modalInstance = $uibModal.open({
                animation: $scope.animationsEnabled,
                templateUrl: setTemplate,
                controller: 'ModalInstanceCtrl',
                size: size,
                resolve: {
                    items: function () {
                        return $scope.items;
                    }
                }
            });

            modalInstance.result.then(function (selectedItem) {
                $scope.selected = selectedItem;
            }, function () {
                $log.info('Modal dismissed at: ' + new Date());
            });
        };

        $scope.toggleAnimation = function () {
            $scope.animationsEnabled = !$scope.animationsEnabled;
        };
    });

    // Please note that $modalInstance represents a modal window (instance) dependency.
    // It is not the same as the $uibModal service used above.
    angular.module('ui.bootstrap.app').controller('ModalInstanceCtrl', function ($scope, $uibModalInstance, items, $rootScope) {

        $scope.items = items;
        $scope.selected = {
            item: $scope.items[0]
        };

        $scope.ok = function () {
            $uibModalInstance.close($scope.selected.item);
        };

        $scope.cancel = function () {
            $uibModalInstance.dismiss('cancel');
        };

        $scope.switchLoginRecover = function () {
            $uibModalInstance.dismiss('cancel');
            $rootScope.$broadcast('modalRecover');
        };

        $scope.switchCadastroModal = function () {
            $uibModalInstance.dismiss('cancel');
            $rootScope.$broadcast('modalCadastro');
        };
    });
</script>
</div>


<script>
    //=== Login configs===
    angular.module('ui.bootstrap.app').controller('loginFormModal', function ($scope, $http) {

        $scope.modalRecover = function () {
            // $scope.$uibModal.dismiss('cancel');
            $uibModalInstance.close($scope.selected.item);
        };
        $scope.cadastrarPage = function () {
            $scope.$emit('cadastrarCtrlOn');
            $scope.$emit('loginCtrlOff');
        };

        $scope.loading = false;
        $scope.entrar = function () {
            $scope.loading = true;
            $scope.messageLogin = '';

            console.log('entrar clicked');

            var request = $http({
                method: "POST",
                url: "/users/login",
                data: {
                    email: $scope.email,
                    pass: $scope.senha,
                    conectado: $scope.conectado,
                },
                headers: {'Content-Type': 'application/x-www-form-urlencoded'}
            }).then(function successCallback(response) {

                if(response.data.dataOk == false){
                    console.log(response);
                    $scope.loading = false;
                    $scope.messageLogin = response.data.message;
                } else if(response.data.dataOk == true) {
                    console.log('logado com sucesso');
                    window.location.reload();
                }
            },function errorCallback(response) {
                console.log('error');
                $scope.loading = false;
            });
        }
    });

    // ======= Register configs validade + http request ============
    angular.module('ui.bootstrap.app').controller('cadastrarCtrl', function ($scope, $http) {

        $scope.loading = false;

        // validacoes no preenchimento
        $scope.validate = function ($setItem) {

            var dataInput = '';
            var dataType = '';

            switch ($setItem){

                case 'cadNome':
//                    console.log('cadNome tested ok!');
                    dataInput = $scope.nome;
                    dataType = 'cadNome';
                    break;
                case 'cadEmail':
                    dataInput = $scope.email;
                    dataType = 'cadEmail';
                    break;
                case 'cadCpfCnpj':
                    dataInput = $scope.cpf_cnpj;
                    dataType = 'cadCpfCnpj';
                    break;
                case 'cadPhone':
                    dataInput = $scope.telefone;
                    dataType = 'cadPhone';
                    break;
                case 'cadPass':
                    dataInput = $scope.senha_1;
                    dataType = 'cadPass';
                    break;
                case 'cadPassC':
                    dataInput = $scope.senha_c;
                    dataInput = {'s1': $scope.senha_1, 's2': $scope.senha_c};
                    dataType = 'cadPassC';
                    break;
            }

            var checkData = $http({
                method: "post",
                url: "/validform",
                data: {
                    dataInput: dataInput,
                    dataType: dataType,
                },
                headers: {'Content-Type': 'application/x-www-form-urlencoded'}
            }).then(function successCallback(response) {

                var inputStatus = response.data.inputOk; // true / false
                var msg = response.data.message;

                switch (dataType){

                    case 'cadNome':
                        if(inputStatus == false){
                            $scope.cadNomeErr = true;
                            $scope.messageCadastro = msg;

                        }else{
                            $scope.cadNomeErr = false;
                            $scope.cadNomeOk = true;
                            $scope.messageCadastro = '';
                        }
                        break;

                    case 'cadEmail':
                        if(inputStatus == false){
                            $scope.cadEmailErr = true;
                            $scope.messageCadastro = msg;
                        }else{
                            $scope.cadEmailErr = false;
                            $scope.cadEmailOk = true;
                            $scope.messageCadastro = '';
                        }
                        break;

                    case 'cadCpfCnpj':
                        if(inputStatus == false){
                            $scope.cadCpfCnpjErr = true;
                            $scope.messageCadastro = msg;
                        }else{
                            $scope.cadCpfCnpjErr = false;
                            $scope.cadCpfCnpjOk = true;
                            $scope.messageCadastro = '';
                        }
                        break;

                    case 'cadPhone':
                        if(inputStatus == false){
                            $scope.cadPhoneErr = true;
                            $scope.messageCadastro = msg;
                        }else{
                            $scope.cadPhoneErr = false;
                            $scope.cadPhoneOk = true;
                            $scope.messageCadastro = '';
                        }
                        break;

                    case 'cadPass':
                        if(inputStatus == false){
                            $scope.cadPassErr = true;
                            $scope.cadPassOk = false;
                            $scope.messageCadastro = msg;
                        }else{
                            $scope.cadPassErr = false;
                            $scope.cadPassOk = true;
                            $scope.messageCadastro = '';
                        }
                        break;

                    case 'cadPassC':
                        if(inputStatus == false){
                            $scope.cadPassCErr = true;
                            $scope.cadPassC_Ok = false;
                            $scope.messageCadastro = msg;
                        }else{
                            $scope.cadPassCErr = false;
                            $scope.cadPassC_Ok = true;
                            $scope.messageCadastro = '';
                        }
                        break;
                }

            }, function errorCallback(response) {
                console.log('error');
            });
        }; // fecha validate


        //ao clicar em cadastrar
        $scope.cadastrar = function ($rootScope) {

            $scope.loading = true;
            $scope.registerBtnDisabled = true;
            $scope.messageCadastro = '';

            var request = $http({
                method: "post",
                url: "/users/register",
                data: {
                    nome: $scope.nome,
                    email: $scope.email,
                    cpf_cnpj: $scope.cpf_cnpj,
                    telefone: $scope.telefone,
                    pass: $scope.senha_1,
                    pass_c: $scope.senha_c,
                },
                headers: {'Content-Type': 'application/x-www-form-urlencoded'}
            }).then(function successCallback(response) {

                var msg = response.data.message;
                console.log(msg);
                $scope.loading = false;
                $scope.messageCadastro = msg;
                $scope.registerBtnDisabled = false;

                if(response.data.registerOk == true){
                    $scope.messageCadastro = 'Cadastro realizado com sucesso';
                    $scope.registerBtnDisabled = true;
                    alert('Cadastro realizado com sucesso!');
                    window.location = "/";
                }

            }, function errorCallback(response) {
                console.log('error');
                $scope.registerBtnDisabled = false;
            });
        }
    });

    // === Recover configs ===
    angular.module('ui.bootstrap.app').controller('recoverCtrl', function ($scope, $http) {

        $scope.loading = false;
        document.getElementById("noticeRecoverCtrl").reset();

        $scope.recover = function ($rootScope) {

            $scope.loading = true;
            document.getElementById("messageCadastrar1").textContent = "";


            //alert($scope.email);
            var request = $http({
                method: "post",
                url: "/users/recover",
                data: {
                    email: $scope.email,
                },
                headers: {'Content-Type': 'application/x-www-form-urlencoded'}
            });
            /* Check whether the HTTP Request is successful or not. */
            request.success(function (data) {
                $scope.loading = false;
                document.getElementById("messageCadastrar1").textContent = data;

                var cad_command = angular.fromJson(data);

                if (cad_command == true) {

                    document.getElementById("messageCadastrar1").style.display = 'none';
                    $scope.$emit('noticeCtrlOn');
                    $scope.$emit('recoverOff');
                    // alert(data);
                    // window.location = "/";
                }
            });
            request.error(function (data) {
                document.getElementById("messageCadastrar1").textContent = "Houve um problema [" + data + "]";
            });
        }
    });
</script>