<!-- carousel -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

        <?php
        $setActive = 0;
        $slideActive = '';

        foreach ($slides as $slideData){
            if($setActive === 0){
                $slideActive = ' active';
            }
            echo '
                    <div class="item '.$slideActive.'">
                       <img src="/directory/'.DB_PROFILE.'/images/'.$slideData->getImagemId()->getId().'.'.$slideData->getImagemId()->getExt().'">
                    </div>
                ';
            $setActive = 1;
            $slideActive = '';
        }
        ?>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!-- fecha carousel-->

<div class="panel panel-default">
    <div class="panel-body">
        <b>Promoções</b>
    </div>
</div>

<div class="panel panel-default">
    <!--    #####Frame de produtos #############-->
    <div class="panel-body">
        <?php

        foreach ($products as $productInfo){
            echo '                
                        <div class="frame-product">
                            <div class="product-thumb">photo</div>
                            <div class="product-title">'.substr($productInfo["nome"],0,50).'</div>
                            <div class="prev-price">De <strike>R$ '.$productInfo["precounitario"].'</strike></div>
                            <div class="current-price">R$ '.$productInfo["precopromocional"].'</div>
                            <div class="drop-price">10x '.$productInfo["precopromocional"] / 10 .' sem juros!</div>
                        </div>                
                
                ';
        }
        ?>
        <div class="clear"></div>

    </div>
    <!--    ### final frame produtos ####-->
</div>


<div class="panel panel-default">
    <div class="panel-body">
        <b>Categorias mais acessadas</b>
    </div>
</div>

<div class="panel panel-default">
    <!--    #####Frame de produtos #############-->
    <div class="panel-body">
        <?php

        foreach ($products as $productInfo){
            echo '                
                    <div class="frame-product">
                        <div class="product-thumb">photo</div>
                        <div class="product-title">'.substr($productInfo["nome"],0,50).'</div>
                        <div class="prev-price">De <strike>R$ '.$productInfo["precounitario"].'</strike></div>
                        <div class="current-price">R$ '.$productInfo["precopromocional"].'</div>
                        <div class="drop-price">10x '.$productInfo["precopromocional"] / 10 .' sem juros!</div>
                    </div>                
                ';
        }
        ?>
        <div class="clear"></div>

    </div>
    <!--    ### final frame produtos ####-->
</div>