<style>
    #slides_control > div{
        height: auto;
    }
    img{
        margin:auto;
        width: 100%;
    }
    #slides_control {
        position:relative;
        width: 100%;
    }
</style>

<div>
    <div ng-cloak ng-controller="CarouselDemoCtrl" id="slides_control">
        <div>
            <carousel interval="myInterval">
                <slide ng-repeat="slide in slides" active="slide.active">
                    <img ng-src="{{slide.image}}">
                </slide>
            </carousel>
        </div>
    </div>
</div>
<script>
    angular.module('ui.bootstrap.app').controller('CarouselDemoCtrl', function ($scope){
        $scope.myInterval = 5000;
        $scope.slides = [
            <?php
            foreach ($slides as $slideData) {
                echo '                
                        {
                            image: "/directory/' . DB_PROFILE . '/images/' . $slideData->getImagemId()->getId() . '.' . $slideData->getImagemId()->getExt() . '"
                        },                
                ';
            }
            ?>
        ];
    })
</script>

<div class="panel panel-default">
    <div class="panel-body">
        <b>Promoções</b>
    </div>
</div>

<div class="panel">
    <!--    #####Frame de produtos #############-->
    <div class="panel-body">
        <?php
        foreach ($products as $productInfo) {
            echo '                
                        <div class="frame-product">
                            <div class="product-thumb">photo</div>
                            <div class="product-title">' . substr($productInfo["nome"], 0, 50) . '</div>
                            <div class="prev-price">De <strike>R$ ' . $productInfo["precounitario"] . '</strike></div>
                            <div class="current-price">R$ ' . $productInfo["precopromocional"] . '</div>
                            <div class="drop-price">10x ' . $productInfo["precopromocional"] / 10 . ' sem juros!</div>
                        </div>
                    
                    ';
        }
        ?>
        <div class="clear"></div>

    </div>
    <!--    ### final frame produtos ####-->
</div>

<div class="banner-promo2">Banner promocional</div>

<div class="panel panel-default">
    <div class="panel-body">
        <b>Categorias mais acessadas</b>
    </div>
</div>

<div class="panel">
    <!--    #####Frame de produtos #############-->
    <div class="panel-body">
        <?php
        foreach ($products as $productInfo) {
            echo '                
                        <div class="frame-product">
                            <div class="product-thumb">photo</div>
                            <div class="product-title">' . substr($productInfo["nome"], 0, 50) . '</div>
                            <div class="prev-price">De <strike>R$ ' . $productInfo["precounitario"] . '</strike></div>
                            <div class="current-price">R$ ' . $productInfo["precopromocional"] . '</div>
                            <div class="drop-price">10x ' . $productInfo["precopromocional"] / 10 . ' sem juros!</div>
                        </div>                
                    ';
        }
        ?>
        <div class="clear"></div>
    </div>
    <!--    ### final frame produtos ####-->
</div>

<div class="banner-promo2">Banner promocional 2</div>
<div class="atend-bar">Barra de atendimento</div>
<!--<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"></script>-->
<!--<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.10.0/ui-bootstrap-tpls.min.js"></script>-->