<!-- Le styles -->
<?= $this->headLink()
    ->appendStylesheet($this->basePath('templates/'.TEMPLATE.'/menu/dropdown.css'))
    ->appendStylesheet($this->basePath('templates/'.TEMPLATE.'/menu/default.css'))
    ->appendStylesheet($this->basePath('templates/'.TEMPLATE.'/menu/default.ultimate.css'))
?>
<!-- / END -->
<ul id="nav" class="dropdown dropdown-horizontal">
    <li id="n-home"><a href="http://www.lwis.net/free-css-drop-down-menu/">Home</a></li>
    <li id="n-music"><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Telefonia</a>
        <ul>
            <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Artists</a>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Browse All Artists</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV.com Picks</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Most Popular Artists</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">New Artists</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Artist Photos</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">A.D.D. Bio</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">First Ladies</a></li>
                </ul>
            </li>
            <li><span class="dir">Music Videos</span>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV.com Video Picks</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Video Premieres</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Most Popular Videos</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Playlists</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Top Videos by Year</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Live Performances</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">The Big Ten</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Headbangers Ball</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Playlibs</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Subterranean</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Sucker Free</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Video Remixer</a></li>
                </ul>
            </li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Your Music on MTV?</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Lyrics</a>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Search for Lyrics</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Play Lyrics Game</a></li>
                </ul>
            </li>
            <li><span class="dir">Music Blogs</span>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Buzzworthy Blog</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Headbangers Blog</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Play | Rhapsody Blog</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Subterranean Blog</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Sucker Free Blog</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">You R Here Blog</a></li>
                </ul>
            </li>
            <li><span class="dir">Music Shows</span>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Dew Circuit Breakout</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Discover &amp; Download</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV Live</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Spankin' New Music Week</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">TRL</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Unplugged</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Yo! MTV Raps</a></li>
                </ul>
            </li>
            <li><span class="dir">Songs</span>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">The Leak |<br>Album Previews</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Free Downloads</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV Radio</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Listen on Rhapsody</a></li>
                </ul>
            </li>
            <li><span class="dir">Genres</span>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Rock</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Pop</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Hip-Hop</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Soul/R&amp;B</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Indie</a></li>
                </ul>
            </li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Billboard Charts</a></li>
        </ul>
    </li>


    <li id="n-shows"><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Informática</a>


        <ul class="submenu">
            <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/"><strong>Notebooks</strong></a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Computadores</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Multifuncionais</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Be on MTV</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Shop MTV Shows</a></li>
<!--            <div style=" height: 200px; width: 500px; background-color: #2aabd2;">banner promocional</div>-->
        </ul>

    </li>




    <li id="n-news"><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">News</a>
        <ul>
            <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">News Main</a></li>
            <li><span class="dir">Headlines</span>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Breaking News</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Music News</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Movie News</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Video Game News</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">World/National News</a></li>
                </ul>
            </li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Video Updates &amp; Interviews</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Newsroom Blog</a></li>
            <li><span class="dir">Live Music Coverage</span>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Your Uploads</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">You R Here Blog</a></li>
                </ul>
            </li>
            <li><span class="dir">MTV Reporters</span>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Liz Hernandez</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Tim Kash</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Kurt Loder</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">John Norris</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">SuChin Pak</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Sway</a></li>
                </ul>
            </li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Video Games Blog</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Street Team '08</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Hottest MCs</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">News Alerts</a></li>
        </ul>
    </li>
    <li id="n-movies"><span class="dir">Movies, Games &amp; More</span>
        <ul>
            <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Movies</a>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Movies Main</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">2008 Movie Awards</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Movies News</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Movies Blog</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Trailers</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Kurt Loder Film Reviews</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Summer Movies</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Interviews</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Red Carpet &amp; On Set Photos</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV Movies Shop</a></li>
                </ul>
            </li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Video Games</a>
                <ul>
                    <li class="first"><span class="dir">Features</span>
                        <ul>
                            <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Rock Band</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">The Dime</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Hot Trailers</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">The G-Hole</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Trailers and Game Videos</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Podcast</a></li>
                        </ul>
                    </li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">News</a>
                        <ul>
                            <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Multiplayer Blog</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Multiplayer Video</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Games News</a></li>
                        </ul>
                    </li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Gamer's Week</a></li>
                </ul>
            </li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Online Games</a>
                <ul>
                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Action Games</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Brain Games</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Classic Games</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV Original Games</a></li>
                </ul>
            </li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Activism</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Mobile</a>
                <ul>
                    <li class="first"><span class="dir">MTV Shows</span>
                        <ul>
                            <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">A.D.D. Bio</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Beavis and Butthead</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">The Hills</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Kaya</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV2</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">mtvU</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Run's House</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Sucker Free on MTV</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">TRL</a></li>
                            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Yo Momma</a></li>
                        </ul>
                    </li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Ringtones</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Graphics</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Games</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Alerts</a></li>
                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Video</a></li>
                </ul>
            </li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Contest &amp; Sweepstakes</a></li>
        </ul>
    </li>
</ul>