<!-- Le styles -->
<?= $this->headLink()
    ->appendStylesheet($this->basePath('templates/'.TEMPLATE.'/menu/dropdown.css'))
    ->appendStylesheet($this->basePath('templates/'.TEMPLATE.'/menu/default.css'))
    ->appendStylesheet($this->basePath('templates/'.TEMPLATE.'/menu/default.ultimate.css'))
?>
<!-- / END -->
<ul id="nav" class="dropdown dropdown-horizontal">
    <li id="n-home"><a href="http://www.lwis.net/free-css-drop-down-menu/">Home</a></li>
<!--    <li id="n-music"><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Telefonia</a>-->
<!--        <ul>-->
<!--            <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Artists</a>-->
<!--                <ul>-->
<!--                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Browse All Artists</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV.com Picks</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Most Popular Artists</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">New Artists</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Artist Photos</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">A.D.D. Bio</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">First Ladies</a></li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li><span class="dir">Music Videos</span>-->
<!--                <ul>-->
<!--                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV.com Video Picks</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Video Premieres</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Most Popular Videos</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Playlists</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Top Videos by Year</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Live Performances</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">The Big Ten</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Headbangers Ball</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Playlibs</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Subterranean</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Sucker Free</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Video Remixer</a></li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Your Music on MTV?</a></li>-->
<!--            <li><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Lyrics</a>-->
<!--                <ul>-->
<!--                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Search for Lyrics</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Play Lyrics Game</a></li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li><span class="dir">Music Blogs</span>-->
<!--                <ul>-->
<!--                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Buzzworthy Blog</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Headbangers Blog</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Play | Rhapsody Blog</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Subterranean Blog</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Sucker Free Blog</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">You R Here Blog</a></li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li><span class="dir">Music Shows</span>-->
<!--                <ul>-->
<!--                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Dew Circuit Breakout</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Discover &amp; Download</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV Live</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Spankin' New Music Week</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">TRL</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Unplugged</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Yo! MTV Raps</a></li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li><span class="dir">Songs</span>-->
<!--                <ul>-->
<!--                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">The Leak |<br>Album Previews</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Free Downloads</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">MTV Radio</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Listen on Rhapsody</a></li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li><span class="dir">Genres</span>-->
<!--                <ul>-->
<!--                    <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/">Rock</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Pop</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Hip-Hop</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Soul/R&amp;B</a></li>-->
<!--                    <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Indie</a></li>-->
<!--                </ul>-->
<!--            </li>-->
<!--            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Billboard Charts</a></li>-->
<!--        </ul>-->
<!--    </li>-->


    <li id="n-shows"><a href="http://www.lwis.net/free-css-drop-down-menu/" class="dir">Informática</a>
        <ul class="submenu">
            <li class="first"><a href="http://www.lwis.net/free-css-drop-down-menu/"><strong>Notebooks</strong></a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Computadores</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Multifuncionais</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Be on MTV</a></li>
            <li><a href="http://www.lwis.net/free-css-drop-down-menu/">Shop MTV Shows</a></li>
<!--            <div style=" height: 200px; width: 500px; background-color: #2aabd2;">banner promocional</div>-->
        </ul>

    </li>

</ul>