<!-- Le styles -->
<?= $this->headLink()
    ->appendStylesheet($this->basePath('templates/'.TEMPLATE.'/menu/dropdown.css'))
    ->appendStylesheet($this->basePath('templates/'.TEMPLATE.'/menu/default.ultimate.css'))
?>
<!--    menu renderizado como servico ##### -->
<div class="menu-container-background">
    <div class="menu-container">
        <div class="cart-buttom"><span class="glyphicon glyphicon-shopping-cart"></span></div>

        <div class="cart-info">
            Seu carrinho esta vazio!
        </div>


        <div class="logo">Logotype</div>
        <ul id="nav" class="dropdown dropdown-horizontal">
        <!--    <li id="n-home"><a href="#">Home</a></li>-->
        <?php

            $menuData =  $this->mainMenu()->renderMenu();
            $initItem = 0;
            $setItemFirst = 'class="first"';

            foreach ($menuData['category'] as $category => $categoryData){

                echo '<li id="n-shows"><a href="#" class="dir">'.$categoryData['nome'].'</a>';

                foreach ($menuData['subCategorias'] as $subCategorias => $getCategoria) {

                    if($categoryData['cat_pai_id'] ==  $subCategorias) {

                    echo '<ul class="submenu">';

                        echo '<div>
                                <img src="/directory/'.DB_PROFILE.'/images/'.$categoryData['img_data'].'.'.$categoryData['ext'].'" class="banner-category">
                             </div>';

                        foreach ($getCategoria as $sub) {

                            if($initItem == 0){
                                $setItemFirst = 'class="first"';
                            }
                        echo '<li '.$setItemFirst.'><a href="#"><strong>'.$sub->getNome().'</strong></a></li>';
                            $setItemFirst = '';
                            $initItem = 1;
                        }
                        echo ' <!--<div style=" height: 200px; width: 500px; background-color: #2aabd2;">banner promocional</div>--></ul>';
                    }
                }
                echo '</li>';
            }

        ?>
        <!-- / END -->
        </ul>

    </div>
    <div class="clear"></div>
</div>