<?= $this->doctype() ?>
<html ng-app="ui.bootstrap.app">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('InterCommerce template :: Varejo')->setSeparator(' - ')->setAutoEscape(false) ?>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.3/angular.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-animate.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-touch.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-sanitize.js"></script>
        <script src="https://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.5.0.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.2.0.min.js"></script>

        <script>
            angular.module('ui.bootstrap.app', ['ui.bootstrap']);
        </script>
        <?= $this->headScript()
//            ->prependFile($this->basePath('templates/'.TEMPLATE.'/js/bootstrap.js'))
//        ->prependFile($this->basePath('templates/'.TEMPLATE.'/js/angular-animate.js'))
//        ->prependFile($this->basePath('templates/'.TEMPLATE.'/js/angular.js'))
//            ->appendFile($this->basePath('templates/' . TEMPLATE . '/js/execUserModals.js'))

        ?>
        <?= $this->headLink()
           ->appendStylesheet($this->basePath('templates/' . TEMPLATE . '/css/login.min.css'))
            ->prependStylesheet($this->basePath('templates/' . TEMPLATE . '/css/home.min.css'))
//            ->appendStylesheet($this->basePath('templates/' . TEMPLATE . '/css/structure.min.css'))
            ->appendStylesheet($this->basePath('templates/' . TEMPLATE . '/css/modalUserStyle.css'))
            ->appendStylesheet($this->basePath('templates/' . TEMPLATE . '/css/style.css'))
        ?>

    </head>
    <body>

        <?php echo $this->partial('headBar'); ?>
        <div class="clear"></div>
        <?php echo $this->partial('menu'); ?>
        <div class="clear"></div>
        <div class="container1320">
            <?= $this->content ?>
        </div>
        <footer>

            <div class="info-container">
                <div class="info first">
                    <!-- List group -->
                    <ul>
                        <li class="title">Info</li>
                        <li>Cras justo odio</li>
                        <li>Entrega</li>
                        <li>Garantia estendida</li>
                        <li>Assessoria de imprensa</li>
                        <li>Investidores</li>
                        <li>Companhia verde</li>

                    </ul>
                </div>

                <div class="info">

                <!-- List group -->
                <ul>
                    <li class="title">FAQ</li>
                    <li>Cras justo odio</li>
                    <li>Entrega</li>
                    <li>Garantia estendida</li>
                    <li>Assessoria de imprensa</li>
                    <li>Investidores</li>
                    <li>Companhia verde</li>

                </ul>
                </div>

                <div class="info">

                <!-- List group -->
                <ul>
                    <li class="title">Loja</li>
                    <li>Cras justo odio</li>
                    <li>Entrega</li>
                    <li>Garantia estendida</li>
                    <li>Assessoria de imprensa</li>
                    <li>Investidores</li>
                    <li>Companhia verde</li>

                </ul>
                </div>
                <div class="clear"></div>

                <div class="credit-cards-container"></div>

                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </div>
        </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
