<?= $this->doctype() ?>
<html lang="en" ng-app="shop">
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <meta charset="utf-8">
        <?= $this->headTitle('InterCommerce Template :: Varejo')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])

            ->prependStylesheet($this->basePath('templates/'.TEMPLATE.'/css/bootstrap-theme.css'))
            ->prependStylesheet($this->basePath('templates/'.TEMPLATE.'/css/bootstrap.css'))
            ->appendStylesheet($this->basePath('templates/'.TEMPLATE.'/css/style.css'))
        ?>
        <!-- Scripts -->
        <?= $this->headScript()
//            ->prependFile($this->basePath('templates/'.TEMPLATE.'/js/bootstrap.js'))
            ->prependFile($this->basePath('templates/'.TEMPLATE.'/js/angular-animate.js'))
            ->prependFile($this->basePath('templates/'.TEMPLATE.'/js/angular.js'))

        ?>

        <!--<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js"></script>-->
        <!--        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular-animate.min.js"></script>-->


        <script>
            angular.module('shop', ['ui.bootstrap']);
        </script>
    </head>
    <body>

        <?php echo $this->partial('menu'); ?>
        <div class="clear"></div>
        <div class="container1320">
            <?= $this->content ?>
        </div>
        <footer>

            <div class="info-container">
                <div class="info first">
                    <!-- List group -->
                    <ul>
                        <li class="title">Info</li>
                        <li>Cras justo odio</li>
                        <li>Entrega</li>
                        <li>Garantia estendida</li>
                        <li>Assessoria de imprensa</li>
                        <li>Investidores</li>
                        <li>Companhia verde</li>

                    </ul>
                </div>

                <div class="info">

                <!-- List group -->
                <ul>
                    <li class="title">FAQ</li>
                    <li>Cras justo odio</li>
                    <li>Entrega</li>
                    <li>Garantia estendida</li>
                    <li>Assessoria de imprensa</li>
                    <li>Investidores</li>
                    <li>Companhia verde</li>

                </ul>
                </div>

                <div class="info">

                <!-- List group -->
                <ul>
                    <li class="title">Loja</li>
                    <li>Cras justo odio</li>
                    <li>Entrega</li>
                    <li>Garantia estendida</li>
                    <li>Assessoria de imprensa</li>
                    <li>Investidores</li>
                    <li>Companhia verde</li>

                </ul>
                </div>
                <div class="clear"></div>

                <div class="credit-cards-container"></div>

                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </div>
        </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
