<?= $this->doctype() ?>
<html ng-app="ui.bootstrap.app">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('InterCommerce template :: '.TEMPLATE.'')->setSeparator(' - ')->setAutoEscape(false) ?>
        <!--<link href="//netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>-->
<!--        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.3/angular.min.js"></script>-->
        <!--<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-animate.min.js"></script>-->
<!--        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-touch.min.js"></script>-->
<!--        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.1/angular-sanitize.js"></script>-->
        <!--<script src="https://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.5.0.min.js"></script>-->
        <!--<script src="https://code.jquery.com/jquery-3.2.0.min.js"></script>-->
        <script src="<?php echo '/templates/' . TEMPLATE . '/js/jquery-3.2.0.js'; ?>"></script>


        <?= $this->headScript()
            ->prependFile($this->basePath('templates/'.TEMPLATE.'/js/angular.js'))
            ->prependFile($this->basePath('templates/'.TEMPLATE.'/js/bootstrap.js'))
//            ->prependFile($this->basePath('templates/'.TEMPLATE.'/js/angular-animate.js'))
            ->appendFile($this->basePath('templates/' . TEMPLATE . '/js/execUserModals.js'))

        ?>
        <!--<script src="https://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.5.0.min.js"></script>-->
        <script src="<?php echo '/templates/' . TEMPLATE . '/js/ui-bootstrap-tpls-2.5.0.js'; ?>"></script>
        <?= $this->headLink()
           ->appendStylesheet($this->basePath('templates/' . TEMPLATE . '/css/bootstrap.min.css'))
           ->appendStylesheet($this->basePath('templates/' . TEMPLATE . '/css/login.min.css'))
            ->prependStylesheet($this->basePath('templates/' . TEMPLATE . '/css/home.min.css'))
//            ->appendStylesheet($this->basePath('templates/' . TEMPLATE . '/css/structure.min.css'))
            ->appendStylesheet($this->basePath('templates/' . TEMPLATE . '/css/modalUserStyle.css'))
            ->appendStylesheet($this->basePath('templates/' . TEMPLATE . '/css/style.css'))
        ?>
        <script>
            //angular.module('ui.bootstrap.app', ['ui.bootstrap']);
        </script>

    </head>
    <body>

        <?php echo $this->partial('headBar'); ?>
        <div class="clear"></div>
        <?php echo $this->partial('menu'); ?>
        <div class="clear"></div>
        <div class="container1320">
            <?= $this->content ?>
        </div>
        <?php echo $this->partial('footer'); ?>
        <?= $this->inlineScript() ?>
    </body>
</html>
