<!-- carousel -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="<?= $this->basePath('directory/intercom.com.br/images/slide_blue-1.jpg') ?>">
        </div>

        <div class="item">
            <img src="<?= $this->basePath('directory/intercom.com.br/images/slide_blue-1.jpg') ?>">
        </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!-- fecha carousel-->




<br><br>

<div class="panel panel-default">
    <div class="panel-body">
        Mais vendidos
    </div>
</div>

<div class="panel panel-default">
<!--    #####Frame de produtos #############-->
    <div class="panel-body">

        <div class="frame-product">
            <div class="product-thumb">photo</div>
            <div class="product-title">Smartphone Samsung Galaxy S7 Android 6.0 Tela 5.1" 32GB 4G</div>
            <div class="prev-price">De <strike>R$ 1.999,00</strike></div>
            <div class="current-price">R$ 1.299,00</div>
            <div class="drop-price">10x 129,00 sem juros!</div>
        </div>

        <div class="frame-product">
            <div class="product-thumb">photo</div>
            <div class="product-title">Smartphone Samsung Galaxy S7 Android 6.0 Tela 5.1" 32GB 4G</div>
            <div class="prev-price">De <strike>R$ 1.999,00</strike></div>
            <div class="current-price">R$ 1.299,00</div>
            <div class="drop-price">10x 129,00 sem juros!</div>
        </div>

        <div class="frame-product">
            <div class="product-thumb">photo</div>
            <div class="product-title">Smartphone Samsung Galaxy S7 Android 6.0 Tela 5.1" 32GB 4G</div>
            <div class="prev-price">De <strike>R$ 1.999,00</strike></div>
            <div class="current-price">R$ 1.299,00</div>
            <div class="drop-price">10x 129,00 sem juros!</div>
        </div>

        <div class="frame-product">
            <div class="product-thumb">photo</div>
            <div class="product-title">Smartphone Samsung Galaxy S7 Android 6.0 Tela 5.1" 32GB 4G</div>
            <div class="prev-price">De <strike>R$ 1.999,00</strike></div>
            <div class="current-price">R$ 1.299,00</div>
            <div class="drop-price">10x 129,00 sem juros!</div>
        </div>

        <div class="clear"></div>

    </div>
<!--    ### final frame produtos ####-->

    <!--    #####Frame de produtos #############-->
    <div class="panel-body">

        <div class="frame-product">
            <div class="product-thumb">photo</div>
            <div class="product-title">Smartphone Samsung Galaxy S7 Android 6.0 Tela 5.1" 32GB 4G</div>
            <div class="prev-price">De <strike>R$ 1.999,00</strike></div>
            <div class="current-price">R$ 1.299,00</div>
            <div class="drop-price">10x 129,00 sem juros!</div>
        </div>

        <div class="frame-product">
            <div class="product-thumb">photo</div>
            <div class="product-title">Smartphone Samsung Galaxy S7 Android 6.0 Tela 5.1" 32GB 4G</div>
            <div class="prev-price">De <strike>R$ 1.999,00</strike></div>
            <div class="current-price">R$ 1.299,00</div>
            <div class="drop-price">10x 129,00 sem juros!</div>
        </div>

        <div class="frame-product">
            <div class="product-thumb">photo</div>
            <div class="product-title">Smartphone Samsung Galaxy S7 Android 6.0 Tela 5.1" 32GB 4G</div>
            <div class="prev-price">De <strike>R$ 1.999,00</strike></div>
            <div class="current-price">R$ 1.299,00</div>
            <div class="drop-price">10x 129,00 sem juros!</div>
        </div>

        <div class="frame-product">
            <div class="product-thumb">photo</div>
            <div class="product-title">Smartphone Samsung Galaxy S7 Android 6.0 Tela 5.1" 32GB 4G</div>
            <div class="prev-price">De <strike>R$ 1.999,00</strike></div>
            <div class="current-price">R$ 1.299,00</div>
            <div class="drop-price">10x 129,00 sem juros!</div>
        </div>

        <div class="clear"></div>

    </div>
    <!--    ### final frame produtos ####-->

</div>

